# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pr:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: 'Install dependencies'

  - script: |
      yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
    displayName: 'Run prettier'

  - script: |
      yarn run lint
    displayName: 'Run ESLint'

  - script: |
      yarn test
    displayName: 'Run test'
